export default {
    "extensions":{
        ".mp4":"video",
        ".avi":"video",
        ".mov":"video",
        ".mkv":"video",
        ".m4a":"audio",
        ".mp3":"audio",
        ".jpg":"image",
        ".png":"image",
        ".jpeg":"image",
        ".txt":"text",
        ".json":"text"
    },
    "processors":{
        ".mp4":"Player",
        ".avi":"Player",
        ".mov":"Player",
        ".mkv":"Player",
        ".m4a":"Player",
        ".mp3":"Player",
        ".jpg":"Image",
        ".png":"Image",
        ".jpeg":"Image",
        ".txt":"Text",
        ".json":"Text"
    }
}